#!/usr/bin/env python3
"""Build strontia-plume.json: the Aug 2026 storm as the Strontia profiling sonde saw it.

Reads the Strontia Springs Reservoir profiling sonde export
(../data/Strontia 0407_0819.xlsx, Denver Water provisional data), the USGS daily
summary at the gage above the reservoir (../data/USGS_South_Platte.csv), and the
Foothills influent lab record (../data/FoothillsInfluent.csv). Offline. Needs
openpyxl.

    python3 build_plume.py

Method, kept identical to the "Strontia Plume Depth" write-up so the two agree:
the sonde makes four casts a day, each starting at the bottom (about 44.5 m)
and rising to the surface. The three deepest readings of every cast are dropped
because the instrument stirs up sediment when it starts (spikes to thousands of
NTU that are an artefact of the measurement). Readings are binned by depth into
2 m bins labelled by their centre (1, 3, ... 41), and each day's cell is the
median of that day's readings in that bin, so a single bad reading cannot move
a cell. The depth column is in metres (unlabelled in the file; confirmed by
Denver Water).
"""

import csv
import json
import os
import statistics
from collections import defaultdict
from datetime import date, datetime, timedelta

import openpyxl

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "..", "data")
SONDE_XLSX = os.path.join(DATA, "Strontia 0407_0819.xlsx")
USGS_CSV = os.path.join(DATA, "USGS_South_Platte.csv")
INFLUENT_CSV = os.path.join(DATA, "FoothillsInfluent.csv")
OUT = os.path.join(HERE, "strontia-plume.json")

FIRST_DAY = date(2026, 8, 8)
LAST_DAY = date(2026, 8, 19)
CAST_GAP_MINUTES = 5
DEEPEST_READINGS_DROPPED = 3
BIN_WIDTH = 2.0
BIN_CENTRES = [1 + BIN_WIDTH * i for i in range(21)]

COL_TIME, COL_DEPTH, COL_TURBIDITY = 0, 3, 6


def read_sonde_rows():
    sheet = openpyxl.load_workbook(SONDE_XLSX, read_only=True).active
    return [r for r in sheet.iter_rows(min_row=2, values_only=True)
            if r[COL_TIME] and FIRST_DAY <= r[COL_TIME].date() <= LAST_DAY]


def split_casts(rows):
    casts, previous = [], None
    for row in rows:
        stamp = row[COL_TIME]
        new_cast = previous is None or (stamp - previous) > timedelta(minutes=CAST_GAP_MINUTES)
        if new_cast:
            casts.append([])
        casts[-1].append(row)
        previous = stamp
    return casts


def usable_readings(cast):
    return cast[DEEPEST_READINGS_DROPPED:]


def bin_centre(depth):
    index = int(depth // BIN_WIDTH)
    return 1 + BIN_WIDTH * index


def daily_cells(casts):
    readings = defaultdict(list)
    for cast in casts:
        for row in usable_readings(cast):
            depth, turbidity = row[COL_DEPTH], row[COL_TURBIDITY]
            if depth is None or turbidity is None:
                continue
            centre = bin_centre(depth)
            if centre in BIN_CENTRES:
                readings[(row[COL_TIME].date(), centre)].append(turbidity)
    return {key: round(statistics.median(values), 2) for key, values in readings.items()}


def day_range():
    day = FIRST_DAY
    while day <= LAST_DAY:
        yield day
        day += timedelta(days=1)


def cell_rows(cells):
    return [[cells.get((day, centre)) for centre in BIN_CENTRES] for day in day_range()]


def read_river():
    values = {}
    with open(USGS_CSV) as f:
        for row in csv.DictReader(f):
            day = datetime.strptime(row["Date"], "%m/%d/%Y").date()
            values[day] = (_num(row["Turbidity_Max"]), _num(row["Turbidity_Median"]))
    return ([values.get(day, (None, None))[0] for day in day_range()],
            [values.get(day, (None, None))[1] for day in day_range()])


def read_influent():
    values = {}
    with open(INFLUENT_CSV) as f:
        for row in csv.DictReader(f):
            day = datetime.strptime(row["DATE"], "%m/%d/%Y").date()
            values[day] = (_num(row["TOC_mg_L"]), _num(row["Alk_mg_L"]))
    return ([values.get(day, (None, None))[0] for day in day_range()],
            [values.get(day, (None, None))[1] for day in day_range()])


def _num(text):
    return float(text) if text not in (None, "") else None


def build():
    cells = cell_rows(daily_cells(split_casts(read_sonde_rows())))
    river_max, river_median = read_river()
    toc, alk = read_influent()
    present = [v for row in cells for v in row if v is not None]
    plume = {
        "_comment": "Generated by build_plume.py from the Strontia Springs profiling sonde "
                    "export, the USGS daily summary at gage 06707525, and the Foothills "
                    "influent record (all in ../data). Denver Water provisional data, "
                    "provided as is; terms in ../data/TERMS.md. Each cell is the median "
                    "turbidity (NTU) of one day's readings in a 2 m depth bin, with the "
                    "three deepest readings of every cast dropped. Depth in metres.",
        "dates": [day.isoformat() for day in day_range()],
        "bins": BIN_CENTRES,
        "cells": cells,
        "vmin": min(present), "vmax": max(present),
        "river_max": river_max, "river_median": river_median,
        "toc": toc, "alk": alk,
    }
    with open(OUT, "w") as f:
        json.dump(plume, f, separators=(",", ":"))
    print(f"wrote {OUT}: {len(plume['dates'])} days x {len(BIN_CENTRES)} bins, "
          f"turbidity {plume['vmin']} to {plume['vmax']} NTU")


if __name__ == "__main__":
    build()
