#!/usr/bin/env python3
"""Build the Strontia Springs summer page.

sonde_data.py cleans the sonde export and the upstream series from the repository's
data/ folder (found by walking up from this file), template.html is the page, and the
result is written to index.html beside them. The water level comes from the committed DWR storage record in
water-system-3d/storage-history.json at the repository root.

The quiz under the scene reuses the lessons written for the depth pictures
(map/strontia-lessons.json, generated by analysis/build_lessons.py):
questions, choices, explanations and every number in them come from there. This
script only picks which lessons the scene can carry, the day the scene jumps to for
each, which dots to show, and a sentence saying where to look in the scene. After an
answer the page shows the lesson's own charts, drawn by the lessons page's
strontia-core.js (inlined) from the slices of strontia-profile.json those charts need.

A second tab holds the team's two data pages in frames: another team member's Foothills
prediction dashboard (map/prediction-dashboard.html) and the lessons page "Strontia Springs, by depth"
(map/strontia.html). Each is inlined with its
data and scripts so it opens without a server, unchanged apart from that and its links.

    uv run --with pandas --with openpyxl teams/team-education/build.py
"""
import json
import re
import sys
from pathlib import Path

import pandas as pd

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from sonde_data import ROOT, sonde, upstream  # noqa: E402

MAP = HERE / "map"

# Where to look in the scene, per lesson. No numbers here: those stay in the lesson text.
LOOK = {
    "floats": "Look at the water. Light blue is warm and dark blue is cold. The warm water sits in a band at the top, and it has all summer. Drag the scrubber to check.",
    "oxygen": "The bubbles are dissolved oxygen. Watch the summer run from April into July: the top of the water turns a lighter, warmer blue, and the bubbles thin out.",
    "bottom": "The bubbles are dissolved oxygen. Compare the water near the surface with the deepest water, inside the dashed band at the bottom.",
    "sinks": "Watch the river pouring in at the left. Its colour is its temperature. Today it is colder than every layer of the reservoir, so it slides all the way down to the bottom.",
    "mud": "The brown dots are mud (turbidity). Watch where the river's muddy water goes after it pours in: not the top, not the bottom. The dashed band marks the muddy layer.",
    "fades": "Same brown dots, a few days on. Watch the days after the storm and follow the muddy layer as it sinks and thins out.",
    "minerals": "The small pale flecks are dissolved minerals (conductivity): more flecks, more minerals. The dashed band is the same muddy layer as the last question.",
    "plant": "The Foothills water plant takes its water out of this reservoir. How deep its intake sits decides which layer it draws from. The brown dots are the storm's mud.",
    "together": "The scene shows the real start of spring: already layered, warm on top and cold below, but everything colder than in summer. The storm in this question is made up.",
}
SHOW = {"floats": [], "oxygen": ["do"], "bottom": ["do"], "sinks": ["do"], "mud": ["turb"], "fades": ["turb"],
        "minerals": ["spc"], "plant": ["turb"], "together": ["turb", "do"]}
# Lessons that only make sense in front of the depth pictures on map/strontia.html.
SKIP = {"read", "detective", "tempcorr"}

# Wording that pointed at the depth pictures, said for the scene instead. Each must still match, so a
# change in build_lessons.py fails the build here rather than slipping past.
REWORD = {
    'But the "% full" chart hardly moved.': "But how full of oxygen it was, as a share of the most it could hold, hardly moved.",
    "After the peak, the white dots go deeper each day and the layer gets paler.": "After the peak, the muddy layer goes deeper each day and thins out.",
    "And this picture is corrected to one standard temperature": "And this reading is corrected to one standard temperature",
    "what would the sonde's pictures most likely show?": "what would the sonde most likely show?",
    'and the "% full" line would drop': "and how full it was would drop",
}

LESSON_REF = re.compile(r"\b([Ll])essons? (\d+(?:,? \d+)*(?: and \d+)?)")


def retitle(text, titles):
    """'lesson 3' and 'lessons 5 and 6' name lessons by their number in the full set; the quiz
    shows a subset in its own order, so refer to them by title instead."""
    def sub(m):
        nums = [int(n) for n in re.findall(r"\d+", m.group(2))]
        names = [f"“{titles[n]}”" for n in nums]
        return names[0] if len(names) == 1 else ", ".join(names[:-1]) + " and " + names[-1]
    return LESSON_REF.sub(sub, text)


def reword(text):
    for old, new in REWORD.items():
        text = text.replace(old, new)
    return text


def quiz(s, updf):
    lessons = json.loads((MAP / "strontia-lessons.json").read_text())["lessons"]
    profile = json.loads((MAP / "strontia-profile.json").read_text())
    marks, plant_toc = profile["marks"], profile["plant_toc"]
    by_id = {l["id"]: l for l in lessons}
    titles = {l["n"]: l["title"] for l in lessons if not l.get("bonus")}
    kept = [l for l in lessons if l["id"] not in SKIP]

    # The day the scene jumps to for each lesson, from the same data the lessons were built on.
    prof = lambda k: pd.DataFrame(s["params"][k]["grid"], index=pd.to_datetime(s["days"]), columns=s["depths"]).astype(float)
    band = lambda k, lo, hi: prof(k).loc[:, lo:hi].median(axis=1)
    day = lambda ts: pd.Timestamp(ts).strftime("%Y-%m-%d")
    top_t, deep_t, deep_do = band("temp", 1, 3), band("temp", 40, 44), band("do", 40, 44)
    july = by_id["floats"]["visuals"][0]["highlight"]
    july_days = slice(july["t0"][:10], (pd.Timestamp(july["t1"]) - pd.Timedelta(days=1)).strftime("%Y-%m-%d"))
    early_aug = by_id["sinks"]["visuals"][0]["x"]
    toc = updf["TOC_mg_L"].loc[plant_toc[0][0]:plant_toc[-1][0]]
    when = {
        "floats": {"date": day((top_t - deep_t).loc[july_days].idxmax())},                 # July's most layered day
        "oxygen": {"from": s["days"][0], "date": day(top_t.loc[july_days].idxmax())},      # April to July's warmest surface
        "bottom": {"date": day(deep_do.idxmin())},                                          # least oxygen at the bottom
        "sinks": {"date": day(deep_do.loc[early_aug[0]:early_aug[-1]].idxmax())},           # the deep oxygen peak of early August
        "mud": {"date": marks["reservoir_peak"][:10]},                                      # the reservoir's muddiest cast
        "fades": {"from": marks["reservoir_peak"][:10], "date": s["days"][-1]},            # the peak to the end of the record
        "minerals": {"date": marks["reservoir_peak"][:10]},
        "plant": {"date": day(toc.diff().idxmax())},                                        # the day the plant's TOC jumped
        "together": {"date": s["days"][0]},
    }

    blob = "\n".join(f for l in kept for q in (l.get("questions") or [l["question"]]) for f in [q["prompt"], q["explain"], *(c.get("why_not", "") for c in q["choices"])])
    for old in REWORD:
        assert old in blob, f"reworded phrase no longer in the lessons: {old!r}"
    # Only the heatmap slices the kept lessons draw travel with the page (the whole profile is 1.6 MB).
    need = {(v["view"], v["param"]) for l in kept for v in l["visuals"] if v["type"] == "heat"}
    views = {vk: {**{k: x for k, x in view.items() if k != "params"}, "params": {pk: view["params"][pk] for (vv, pk) in need if vv == vk}}
             for vk, view in profile["views"].items() if any(vv == vk for vv, _ in need)}
    slim = {k: profile[k] for k in ("depths", "params", "service_events", "gage", "plant_toc", "marks", "terms")}
    slim["views"] = views
    out = []
    for l in kept:
        # A highlight on a picture shown only "for comparison" (the what-if) is not about this lesson's day.
        hl = next((v["highlight"] for v in l["visuals"] if v["type"] == "heat" and v.get("highlight") and not v.get("note")), None)
        qs = l.get("questions") or [l["question"]]
        item = {
            "id": l["id"], "title": l["title"], "whatif": bool(l.get("whatif")), **when[l["id"]],
            "show": SHOW[l["id"]], "look": LOOK[l["id"]],
            "band": {"z0": hl["z0"], "z1": hl["z1"], "label": hl["label"]} if hl else None,
            "questions": [{"prompt": retitle(reword(q["prompt"]), titles), "explain": retitle(reword(q["explain"]), titles),
                           "choices": [{"text": c["text"], "correct": c["correct"], "why_not": retitle(reword(c.get("why_not", "")), titles)} for c in q["choices"]]} for q in qs],
            "why": l["why"], "comparison": l.get("comparison"), "care": l.get("care"),
            "visuals": l["visuals"], "orig_look": l["look"],
            # A connection to a lesson the quiz does not carry would point at nothing.
            "connect": retitle(l["connect"], titles) if l.get("connect") and all(int(n) in {k["n"] for k in kept} for n in re.findall(r"\b[Ll]essons? (\d+)", l["connect"])) else None,
        }
        out.append(item)
    return out, slim


def dashboard():
    """The prediction dashboard as one self-contained document: its fetches replaced by the data itself."""
    html = (MAP / "prediction-dashboard.html").read_text()
    for name in ("foothills-prediction", "dashboard-extra"):
        call = f'fetchJson("../dashboard/{name}.json")'
        assert html.count(call) == 1, call
        data = json.loads((HERE / "dashboard" / f"{name}.json").read_text())
        html = html.replace(call, "(" + json.dumps(data, separators=(",", ":")) + ")")
    # The back link points at the map; inside this page's frame there is nothing to go back to.
    flag = 'new URLSearchParams(location.search).get("embedded")'
    assert html.count(flag) == 1
    html = html.replace(flag, "true")
    # Its links to the map are relative to map/; a frame's links resolve against this page's folder.
    link = 'href="design-storm-water-system-3d.html"'
    assert html.count(link) == 2, link
    return html.replace(link, 'href="../map/design-storm-water-system-3d.html" target="_blank" rel="noopener"')


def swap(html, old, new, count=1):
    assert html.count(old) == count, (old, html.count(old))
    return html.replace(old, new)


def depth_page():
    """The lessons page as one document: data and scripts inlined, links pointed at map/."""
    html = (MAP / "strontia.html").read_text()
    for name in ("strontia-profile", "strontia-lessons"):
        data = json.dumps(json.loads((MAP / f"{name}.json").read_text()), separators=(",", ":"))
        html = swap(html, f'fetch("{name}.json")', "({ ok: true, json: async () => (" + data + ") })")
    for js in ("strontia-core.js", "team-chat.js"):
        html = swap(html, f'<script src="{js}"></script>', "<script>\n" + (MAP / js).read_text() + "\n</script>")
    html = swap(html, '<link rel="stylesheet" href="team-chat.css">', "<style>\n" + (MAP / "team-chat.css").read_text() + "\n</style>")
    html = swap(html, 'href="DATA-TERMS.md"', 'href="../map/DATA-TERMS.md"')
    html = swap(html, 'href="design-storm-water-system-3d"', 'href="../map/design-storm-water-system-3d.html" target="_blank" rel="noopener"')
    # Its own Dashboard mode frames the prediction dashboard by path; this page shows that beside it instead.
    return swap(html, '<button type="button" data-mode="dashboard">Dashboard</button>', "")


def main():
    s = sonde()
    first, last = pd.Timestamp(s["days"][0]), pd.Timestamp(s["days"][-1])
    up, updf = upstream(first - pd.Timedelta(days=14), last)
    # Daily storage for Strontia Springs from the map's DWR record, water year 2026 (index 0 is 2025-10-01).
    hist = json.loads((ROOT / "water-system-3d" / "storage-history.json").read_text())["reservoirs"]["STRRESCO"]["years"]["2026"]
    wy0 = pd.Timestamp("2025-10-01")
    up["Storage_AF"] = [(lambda i: hist[i] if 0 <= i < len(hist) else None)((pd.Timestamp(d) - wy0).days) for d in up["dates"]]
    window = updf.loc[first:last]
    presets = [
        {"label": "Spring begins", "date": s["days"][0]},
        {"label": "The big rain", "date": window["PRCP"].idxmax().strftime("%Y-%m-%d")},
        {"label": "Snowmelt peak", "date": window["Flow_CFS"].loc[: "2026-06-30"].idxmax().strftime("%Y-%m-%d")},
        {"label": "Peak river flow", "date": window["Flow_CFS"].idxmax().strftime("%Y-%m-%d")},
        {"label": "The August storm", "date": "2026-08-14"},
        {"label": "Summer ends", "date": s["days"][-1]},
    ]
    q, profile = quiz(s, updf)
    for item in q:
        print(f"{item['id']:10s} {item.get('from', '') or '':10s} -> {item['date']}  show {item['show']}  band {item['band'] and item['band']['label']}")
    payload = {"built": pd.Timestamp.today().strftime("%Y-%m-%d"), "sonde": s, "upstream": up, "presets": presets, "quiz": q, "profile": profile, "dashboard": dashboard(), "depth": depth_page()}
    template = (HERE / "template.html").read_text()
    for marker in ("/*__DATA__*/", "/*__CORE__*/"):
        assert template.count(marker) == 1, marker
    out = HERE / "index.html"
    # "</" inside a JSON string would end the page's script tag early; JavaScript reads "<\/" as the same text.
    out.write_text(template.replace("/*__DATA__*/", json.dumps(payload, separators=(",", ":")).replace("</", "<\\/"))
                   .replace("/*__CORE__*/", (MAP / "strontia-core.js").read_text()))
    print(f"wrote {out} ({out.stat().st_size / 1024:.0f} KB)")


if __name__ == "__main__":
    main()
