#!/usr/bin/env python3
"""Build the River map tab's geometry: src/riverMap/geometry.json.

Reads the basin and river lines the 3D map uses (../../../strontia-brief/, from
USGS NLDI), station coordinates (places.json, SNOTEL metadata), and the
OpenStreetMap reservoir, dam and plant outlines in geo/ (fetched once; see its
_source). Projects them into two SVG frames: the whole basin, and an enlarged
Strontia Springs to Foothills inset, and simplifies each line to about a pixel.
Offline. Run once, like precompute.py.
"""
import json
import math
import os

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.normpath(os.path.join(HERE, '..', '..', '..'))
BRIEF = os.path.join(REPO, 'strontia-brief')
OUT = os.path.join(HERE, 'src', 'riverMap', 'geometry.json')

COS = math.cos(math.radians(39.2))  # one latitude for the whole map is fine at this size


def simplify(pts, tol):
    """Douglas-Peucker on projected points."""
    if len(pts) < 3:
        return pts
    (x1, y1), (x2, y2) = pts[0], pts[-1]
    dx, dy = x2 - x1, y2 - y1
    length = math.hypot(dx, dy)
    best, idx = 0, 0
    for i, (x, y) in enumerate(pts[1:-1], 1):
        d = (abs(dy * x - dx * y + x2 * y1 - y2 * x1) / length) if length else math.hypot(x - x1, y - y1)
        if d > best:
            best, idx = d, i
    if best > tol:
        return simplify(pts[:idx + 1], tol)[:-1] + simplify(pts[idx:], tol)
    return [pts[0], pts[-1]]


class Frame:
    """Equirectangular projection of a lon/lat window into an SVG box."""

    def __init__(self, x0, y0, lon0, lat0, px_per_deg_lon):
        self.x0, self.y0, self.lon0, self.lat0 = x0, y0, lon0, lat0
        self.kx = px_per_deg_lon
        self.ky = px_per_deg_lon / COS

    def xy(self, lon, lat):
        return (round(self.x0 + (lon - self.lon0) * self.kx, 1), round(self.y0 + (self.lat0 - lat) * self.ky, 1))

    def px_per_km(self):
        return round(self.kx / (111.32 * COS), 2)


def line_path(lines, frame, tol):
    parts = []
    for ln in lines:
        pts = simplify([frame.xy(*c) for c in ln], tol)
        if len(pts) >= 2:
            parts.append('M' + ' L'.join(f'{x},{y}' for x, y in pts))
    return ' '.join(parts)


def ring_path(ring, frame, tol):
    # Split a closed ring in two so the simplifier has distinct end points.
    pts = [frame.xy(*c) for c in ring]
    h = len(pts) // 2
    out = simplify(pts[:h + 1], tol)[:-1] + simplify(pts[h:], tol)
    return 'M' + ' L'.join(f'{x},{y}' for x, y in out) + ' Z'


def bbox(ring, frame):
    pts = [frame.xy(*c) for c in ring]
    xs, ys = [x for x, _ in pts], [y for _, y in pts]
    return [min(xs), min(ys), max(xs), max(ys)]


def features(name):
    with open(os.path.join(BRIEF, 'basins', name)) as f:
        return json.load(f)['features']


def main():
    basin = features('south-platte-above-strontia-06707525.json')[0]['geometry']['coordinates'][0]
    upstream = [f['geometry']['coordinates'] for f in features('mainstem-flowlines-06707525.json')]
    downstream = [f['geometry']['coordinates'] for f in features('downstream-mainstem-06707525.json')]
    with open(os.path.join(BRIEF, 'places.json')) as f:
        places = json.load(f)
    with open(os.path.join(HERE, 'geo', 'osm-strontia-foothills.json')) as f:
        osm = {e['id']: e['geometry'] for e in json.load(f)['elements']}
    with open(os.path.join(REPO, 'water-system-3d', 'snotel-co-stations.json')) as f:
        snotel = json.load(f)
    hoosier = next(s for s in snotel if s.get('stationTriplet') == '531:CO:SNTL')

    g, fac = places['gages'], places['facilities']
    points = {
        'hoosier': (hoosier['longitude'], hoosier['latitude']),
        'trumbull': (g['flow']['lon'], g['flow']['lat']),
        'gage': (g['turbidity']['lon'], g['turbidity']['lat']),
        'northFork': (g['north_fork_confluence']['lon'], g['north_fork_confluence']['lat']),
        'intake': (fac['conduit_26_intake']['lon'], fac['conduit_26_intake']['lat']),
        'plant': (fac['foothills_plant']['lon'], fac['foothills_plant']['lat']),
    }
    for key in ('cheesman', 'eleven_mile', 'antero'):
        r = places['reservoirs'][key]
        points[key] = (r['lon'], r['lat'])

    # Whole basin: fits 520 px wide from x=20.
    main = Frame(20, 60, -106.215, 39.62, 520 / 1.21)
    # Inset: Strontia Springs to Foothills, 560 x 600 px.
    inset = Frame(580, 20, -105.22, 39.52, 2800)
    inset_bottom_lat = inset.lat0 - 600 / inset.ky
    inset_right_lon = inset.lon0 + 560 / inset.kx

    geo = {
        '_source': 'Generated by precompute_map.py. Basin and rivers: USGS NLDI. '
                   'Reservoir, dam, plant outlines: (c) OpenStreetMap contributors, ODbL.',
        'viewBox': [0, 0, 1160, 640],
        'main': {
            'basin': ring_path(basin, main, 1.0),
            'upstream': line_path(upstream, main, 0.7),
            'insetBox': list(main.xy(inset.lon0, inset.lat0)) + list(main.xy(inset_right_lon, inset_bottom_lat)),
            'pxPerKm': main.px_per_km(),
            'points': {k: main.xy(*v) for k, v in points.items()},
        },
        'inset': {
            'box': [580, 20, 560, 600],
            'upstream': line_path(upstream, inset, 1.0),
            'downstream': line_path(downstream, inset, 1.0),
            'reservoir': ring_path(osm[42380142], inset, 0.6),
            'dam': line_path([osm[42380149]], inset, 0.5),
            'plant': ring_path(osm[1278299568], inset, 0.5),
            'plantBox': bbox(osm[1278299568], inset),
            'pxPerKm': inset.px_per_km(),
            'points': {k: inset.xy(*v) for k, v in points.items()},
        },
    }
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w') as f:
        json.dump(geo, f, separators=(',', ':'))
    print(f'wrote {OUT} ({os.path.getsize(OUT)} bytes)')
    for frame in ('main', 'inset'):
        print(frame, {k: v for k, v in geo[frame]['points'].items()})


if __name__ == '__main__':
    main()
