"""
Generates dashboard-extra.json: the additional data the standalone prediction
dashboard (../map/prediction-dashboard.html) needs beyond foothills-prediction.json
-- sonde time series, a depth-profile snapshot, the sonde lag-test comparison,
and a compact snapshot of the upstream reservoirs (not the full 2.7MB
reservoir_ops_history.json).

Offline; rerun after ]sonde_daily.csv,
reservoir_ops_history.json, or data/Strontia 0407_0819.xlsx change.

    python teams/team-education/dashboard/build_dashboard_extra.py
"""
import json
import sys
import os

import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, root_mean_squared_error
from sklearn.model_selection import GridSearchCV, TimeSeriesSplit, train_test_split

from model_comparison import build_toc_dataset, build_alk_dataset
from process_sonde_data import CHL_OFFSET_UGL

SONDE_XLSX = "data/Strontia 0407_0819.xlsx"
SONDE_DAILY_CSV = "teams/team-education/dashboard/sonde_daily.csv"
RESERVOIR_OPS_JSON = "teams/team-education/dashboard/reservoir_ops_history.json"
UPSTREAM_RESERVOIRS = ["Antero", "Eleven Mile", "Cheesman", "Dillon"]
OUT = "teams/team-education/dashboard/dashboard-extra.json"

LAGS_TO_TRY = [0, 1, 2, 3, 4]
RF_PARAM_GRID = {
    "n_estimators": [100, 200], "max_depth": [3, 5, 7],
    "min_samples_leaf": [5, 10, 20], "max_features": [1.0, "sqrt"],
}


def sonde_series():
    df = pd.read_csv(SONDE_DAILY_CSV)
    cols = ["temp_c_mean", "turbidity_ntu_mean", "chl_ugl_mean", "phycocyanin_mean", "orp_mv_mean", "odo_mgl_mean"]
    return [{"date": row["DATE"], **{c: round(row[c], 3) for c in cols}} for _, row in df.iterrows()]


def latest_depth_profile():
    """Every reading from the single most recent day's cast(s), sorted by depth."""
    raw = pd.read_excel(SONDE_XLSX, engine="openpyxl")
    raw["date"] = pd.to_datetime(raw["Time stamp"]).dt.date
    latest_date = raw["date"].max()
    day = raw[raw["date"] == latest_date].sort_values("Vertical Position ")
    return {
        "date": str(latest_date),
        "readings": [
            {
                "depth_m": round(r["Vertical Position "], 2),
                "temp_c": round(r["Temp C"], 2),
                "turbidity_ntu": round(r["Turbidity NTU"], 2),
                # Raw fluorometer channel reads ~0.20 ug/L low (see
                # process_sonde_data.py for the calibration-offset analysis);
                # apply the same correction here so this panel matches
                # sonde_daily.csv rather than showing the uncorrected raw value.
                "chl_ugl": round(r["Chl ug/L"] + CHL_OFFSET_UGL, 2),
                "phycocyanin": round(r["Phycocyanin "], 2),
                "orp_mv": round(r["ORP mV"], 2),
            }
            for _, r in day.iterrows()
        ],
    }


def reservoir_snapshot():
    with open(RESERVOIR_OPS_JSON) as f:
        history = json.load(f)
    latest_day = max(history)
    return {"date": latest_day, "reservoirs": {name: history[latest_day].get(name) for name in UPSTREAM_RESERVOIRS}}


def score_rf(X_train, y_train, X_test, y_test, weights):
    search = GridSearchCV(RandomForestRegressor(random_state=42), RF_PARAM_GRID,
                           cv=TimeSeriesSplit(n_splits=5), n_jobs=-1)
    search.fit(X_train, y_train, sample_weight=weights)
    preds = search.best_estimator_.predict(X_test)
    return round(r2_score(y_test, preds), 3), round(root_mean_squared_error(y_test, preds), 3)


def sonde_lag_test(X, y, weight_condition, sonde):
    results = []
    for lag in LAGS_TO_TRY:
        combined = X.join(sonde.shift(lag, freq="D"), how="left").join(y.rename("target")).dropna()
        if len(combined) < 40:
            continue
        base_cols, sonde_cols = list(X.columns), list(sonde.columns)
        y_sub = combined["target"]
        X_train, X_test, y_train, y_test = train_test_split(combined, y_sub, test_size=0.4, shuffle=False)
        weights = np.where(weight_condition(y_train), 1.5, 1.0)
        base_r2, base_rmse = score_rf(X_train[base_cols], y_train, X_test[base_cols], y_test, weights)
        full_r2, full_rmse = score_rf(X_train[base_cols + sonde_cols], y_train,
                                       X_test[base_cols + sonde_cols], y_test, weights)
        results.append({"lag_days": lag, "rows": len(combined), "test_days": len(y_test),
                         "gage_only_r2": base_r2, "gage_only_rmse": base_rmse,
                         "plus_sonde_r2": full_r2, "plus_sonde_rmse": full_rmse})
    return results


if __name__ == "__main__":
    sonde = pd.read_csv(SONDE_DAILY_CSV)
    sonde["DATE"] = pd.to_datetime(sonde["DATE"])
    sonde = sonde.set_index("DATE").sort_index()

    toc_X, toc_y = build_toc_dataset()
    alk_X, alk_y = build_alk_dataset()

    output = {
        "_comment": "Generated by build_dashboard_extra.py. Do not edit by hand.",
        "note": "Sonde-related results here cover only ~104 days (Apr-Aug 2026) and are exploratory, "
                "not production numbers -- see prediction-dashboard.html for the caveats.",
        "sonde_series": sonde_series(),
        "sonde_depth_profile": latest_depth_profile(),
        "reservoir_snapshot": reservoir_snapshot(),
        "sonde_lag_test": {
            "toc": sonde_lag_test(toc_X, toc_y, lambda y: y > 4.0, sonde),
            "alk": sonde_lag_test(alk_X, alk_y, lambda y: y < 60.0, sonde),
        },
    }
    with open(OUT, "w") as f:
        json.dump(output, f, indent=1)
    print(f"Wrote {OUT}")
